const { jsPDF } = require("jspdf");
const fs = require("fs");

const doc = new jsPDF();
const docTitle = "RecoverX: Fraud-Aware Onboarding Engine";
const docSubtitle = "Technical Documentation & System Architecture";

// --- Styling ---
doc.setFont("helvetica", "bold");
doc.setFontSize(22);
doc.setTextColor(229, 57, 53); // RecoverX Red
doc.text(docTitle, 20, 30);

doc.setFontSize(14);
doc.setTextColor(100, 100, 100);
doc.text(docSubtitle, 20, 40);

doc.setDrawColor(200, 200, 200);
doc.line(20, 45, 190, 45);

// --- Sections ---
const sections = [
  {
    title: "1. Core Mission",
    content: "RecoverX is a production-grade AML intelligence layer designed to detect mule accounts at the point of creation. It provides real-time risk scoring (TIS) across 5 intelligence modules."
  },
  {
    title: "2. Key File Descriptions",
    content: "• src/services/onboardingEngine.js: The brain. Handles Identity, Device, Telecom, Velocity, and Behavioral checks.\n• src/pages/Onboarding.jsx: The UI wizard. Manages the 6-phase onboarding flow and decision logic.\n• src/services/mockData.js: Pattern matching backend. Detects ID/Name reuse from existing data.\n• vercel.json: Permanent routing configuration for live deployments."
  },
  {
    title: "3. The 5 Intelligence Modules",
    content: "A. Identity: PAN/Aadhaar validation and multi-account reuse detection.\nB. Device: Fingerprinting, VPN/Proxy detection, and Emulator flagging.\nC. Telecom: Disposable email/phone domain blacklist and newly-activated SIM detection.\nD. Velocity: Signup frequency monitoring per IP and Device ID.\nE. Behavioral: Silent telemetry of keystrokes, paste events, and form completion speed."
  },
  {
    title: "4. Risk Scoring (TIS)",
    content: "Scores are weighted from 0-100. Over 60 triggers a 'HIGH RISK' block, forwarding the case to the investigator queue with a full audit trail."
  }
];

let yPos = 60;
sections.forEach(s => {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text(s.title, 20, yPos);
  yPos += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(50, 50, 50);
  const lines = doc.splitTextToSize(s.content, 170);
  doc.text(lines, 20, yPos);
  yPos += (lines.length * 7) + 10;
});

// --- Footer ---
doc.setFontSize(10);
doc.setTextColor(150, 150, 150);
doc.text("Generated by RecoverX AI Engine - " + new Date().toLocaleDateString(), 20, 280);

const pdfOutput = doc.output();
fs.writeFileSync("RecoverX_Documentation.pdf", pdfOutput, 'binary');
console.log("PDF generated successfully: RecoverX_Documentation.pdf");
